export const USER_IS_NOT_VERIFIED_STATUS_CODE = 422;
export const FILTERS_LIMIT_STATUS_CODE = 423;
export const TOO_MANY_REQUESTS_STATUS_CODE = 429;
export const BAD_REQUEST_STATUS_CODE = 400;
export const TOKEN_ALREADY_USED_STATUS_CODE = 401;
