export const ACTIVATE_PUSH_NOTIFICATIONS = "ACTIVATE_PUSH_NOTIFICATIONS";
export const INITIALIZE_STORE = "INITIALIZE_STORE";
export const INITIAL_SEARCH = "INITIAL_SEARCH";

export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_FILTERS = "SET_FILTERS";
