export const ACTIVATE_PUSH_NOTIFICATIONS = "ACTIVATE_PUSH_NOTIFICATIONS";
export const INITIALIZE_STORE = "INITIALIZE_STORE";
export const INITIAL_SEARCH = "INITIAL_SEARCH";

export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_FILTERS = "SET_FILTERS";

export const SET_APARTMENT_LIST = "SET_APARTMENT_LIST";
export const APPEND_APARTMENT_LIST = "APPEND_APARTMENT_LIST";

export const SET_FOUND_APARTMENT_LIST = "SET_FOUND_APARTMENT_LIST";
export const APPEND_FOUND_APARTMENT_LIST = "APPEND_FOUND_APARTMENT_LIST";
