export const APPEND_APARTMENT_LIST = "APPEND_APARTMENT_LIST";
export const APPEND_FOUND_APARTMENT_LIST = "APPEND_FOUND_APARTMENT_LIST";

export const DECREASE_FOUND_APARTMENTS_COUNTER =
  "DECREASE_FOUND_APARTMENTS_COUNTER";

export const INITIAL_SEARCH = "INITIAL_SEARCH";
export const INITIALIZE_STORE = "INITIALIZE_STORE";

export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_APARTMENT_LIST = "SET_APARTMENT_LIST";
export const SET_CLICKED_FOUND_APARTMENTS = "SET_CLICKED_FOUND_APARTMENTS";
export const SET_FILTERS = "SET_FILTERS";
export const SET_FOUND_APARTMENT_LIST = "SET_FOUND_APARTMENT_LIST";
export const SET_FOUND_APARTMENTS_COUNTER = "SET_FOUND_APARTMENTS_COUNTER";
export const SET_LOADING_APARTMENT_LIST = "SET_LOADING_APARTMENT_LIST";
export const SET_LOADING_FOUND_APARTMENT_LIST =
  "SET_LOADING_FOUND_APARTMENT_LIST";

export const UPDATE_NOTIFICATION_ACTIVATION_ALLOWANCE =
  "UPDATE_NOTIFICATION_ACTIVATION_ALLOWANCE";
export const UPDATE_PUSH_NOTIFICATIONS = "UPDATE_PUSH_NOTIFICATIONS";
